apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-client
spec:
  serviceName: hazelcast-client
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-client
  template:
    metadata:
      labels:
        app: hazelcast-client
    spec:
      serviceAccountName: hazelcast-enterprise-operator
      containers:
        - name: hazelcast-client
          image: <--- HZ_QUARKUS_CLIENT_IMAGE --->
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---

apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  type: LoadBalancer
  selector:
    app: hazelcast-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

